### ISSUE TITLE
Doc issue, wrong pair key `project`

### ISSUE THREAD

**Issue by cmaster11** [aos-dev/go-service-gcs#56]
Hey, not sure where I should post this, but since it's related to the GCS connector, here I am.

In the docs page https://beyondstorage.io/docs/go-storage/services/gcs , you use `project` instead of `project_id` in the connection string, which does not match the right one :)

(for future ref, where should I open issues for docs?)

**Comment by Xuanwo** [comment]
> (for future ref, where should I open issues for docs?)

It's OK to post here, the docs related to gcs is maintained by gcs too.

> In the docs page https://beyondstorage.io/docs/go-storage/services/gcs , you use `project` instead of `project_id` in the connection string, which does not match the right one :)

Yep, we will fix it as soon as possible.

<blockquote><img src="/img/favicon.ico" width="48" align="right"><div><strong><a href="https://beyondstorage.io/docs/go-storage/services/gcs">gcs | BeyondStorage</a></strong></div><div>Google Cloud Storage</div></blockquote>
